coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0
        branches: "!foo"
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: "!foo"
  behavior: default
